import React from 'react';
import { X, Copy, Check, Download, ExternalLink } from 'lucide-react';
import { Project } from '../../types';
import { StorageService } from '../../services/storage';

interface SitemapModalProps {
  projects: Project[];
  isOpen: boolean;
  onClose: () => void;
  mode: 'sitemap' | 'robots';
}

export const SitemapModal: React.FC<SitemapModalProps> = ({
  projects,
  isOpen,
  onClose,
  mode,
}) => {
  const [copied, setCopied] = React.useState(false);
  const customDomain = StorageService.getCustomDomain();
  const baseUrl = customDomain
    ? `https://${customDomain}`
    : typeof window !== 'undefined'
    ? window.location.origin
    : 'https://ellekay.design';
  const currentDate = new Date().toISOString().split('T')[0];

  if (!isOpen) return null;

  // Generate XML Sitemap
  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Core Static Routes -->
  <url>
    <loc>${baseUrl}/</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${baseUrl}/#works</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>${baseUrl}/#services</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>${baseUrl}/#about</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>${baseUrl}/#contact</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  
  <!-- Dynamic Public Project Pages generated by CMS -->
${projects
  .filter((p) => p.isPublished)
  .map(
    (p) => `  <url>
    <loc>${baseUrl}/project/${p.slug}</loc>
    <lastmod>${p.updatedAt ? p.updatedAt.split('T')[0] : currentDate}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${p.isFeatured ? '0.9' : '0.7'}</priority>
  </url>`
  )
  .join('\n')}
</urlset>`;

  // Generate robots.txt
  const robotsTxt = `# robots.txt for Elle Kay Studio
User-agent: *
Allow: /
Disallow: /admin
Disallow: /api/

# Sitemap location
Sitemap: ${baseUrl}/sitemap.xml
`;

  const contentToDisplay = mode === 'sitemap' ? sitemapXml : robotsTxt;
  const fileName = mode === 'sitemap' ? 'sitemap.xml' : 'robots.txt';

  const handleCopy = () => {
    navigator.clipboard.writeText(contentToDisplay);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([contentToDisplay], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 sm:p-8 backdrop-blur-sm">
      <div className="relative w-full max-w-4xl max-h-[90vh] flex flex-col border border-[#ded7cc] bg-[#f9f8f5] rounded-sm overflow-hidden shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[#ded7cc] px-6 py-4 bg-[#f2ede4]">
          <div>
            <h3 className="font-editorial text-xl text-[#18181b]">
              {mode === 'sitemap' ? 'XML Sitemap (Search Engine Optimization)' : 'Robots.txt Configuration'}
            </h3>
            <p className="text-xs text-[#787268]">
              {mode === 'sitemap'
                ? `Automatically indexes all ${projects.filter((p) => p.isPublished).length} published projects from CMS`
                : 'Cloudflare crawlers and bot indexing rules'}
            </p>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-[#787268] hover:text-[#18181b]"
            aria-label="Close"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content viewer */}
        <div className="p-6 overflow-y-auto flex-1 font-mono text-xs text-[#2c2a28] bg-[#efeae0] whitespace-pre selection:bg-[#ded7cc]">
          {contentToDisplay}
        </div>

        {/* Footer actions */}
        <div className="border-t border-[#ded7cc] px-6 py-4 bg-[#f2ede4] flex flex-wrap items-center justify-between gap-4">
          <div className="text-xs text-[#787268]">
            Ready for Cloudflare Pages / Workers deployment root
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 border border-[#ded7cc] bg-[#f9f8f5] px-3.5 py-2 text-xs text-[#18181b] hover:bg-[#e8e2d6] transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-[#2e7d32]" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 bg-[#18181b] text-white px-4 py-2 text-xs font-medium hover:bg-[#33312e] transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download {fileName}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
